### ISSUE TITLE
'G2ModuleException' is not defined

### ISSUE THREAD

**Issue by docktermj** [Senzing/configurator#80]
Seen when running https://github.com/Senzing/kubernetes-demo/

```
2022-09-30 17:17:34,265 senzing-50090297I Enter {"config_path": "/etc/opt/senzing", "debug": false, "g2_internal_database": null, "host": "0.0.0.0", "port": "8253", "program_updated": "2022-09-29", "program_version": "1.1.6", "senzing_sdk_version_major": null, "sleep_time_in_seconds": 0, "start_time": 1664558254.2653804, "subcommand": "service", "support_path": "/opt/senzing/data"}
* Serving Flask app 'configurator'
* Debug mode: off
2022-09-30 17:17:34,266 [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
* Running on all addresses (0.0.0.0)
* Running on http://127.0.0.1:8253
* Running on http://172.17.0.18:8253
2022-09-30 17:17:34,266 [33mPress CTRL+C to quit[0m
2022-09-30 17:25:20,538 Exception on /datasources [GET]
Traceback (most recent call last):
File "/app/configurator.py", line 940, in get_g2_config
result = G2Config()
NameError: name 'G2Config' is not defined
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/app/venv/lib/python3.9/site-packages/flask/app.py", line 2525, in wsgi_app
response = self.full_dispatch_request()
File "/app/venv/lib/python3.9/site-packages/flask/app.py", line 1822, in full_dispatch_request
rv = self.handle_user_exception(e)
File "/app/venv/lib/python3.9/site-packages/flask/app.py", line 1820, in full_dispatch_request
rv = self.dispatch_request()
File "/app/venv/lib/python3.9/site-packages/flask/app.py", line 1796, in dispatch_request
return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
File "/app/configurator.py", line 1067, in http_get_datasources
g2_client = get_g2_client(config)
File "/app/configurator.py", line 1019, in get_g2_client
g2_config = get_g2_config(config)
File "/app/configurator.py", line 952, in get_g2_config
except G2ModuleException as err:
NameError: name 'G2ModuleException' is not defined
```

**Comment by docktermj** [comment]
Fixed via https://github.com/Senzing/configurator/issues/58
